### PR TITLE
Move model SQL to models

### PR DESCRIPTION
**Pull request by clrcrl**
Moves the modeling SQL out of adapter macros and into models.

In the future:
- If a model has a few lines of code that need to be adapted for each warehouse, adapter macros should still be used (for those lines of code only)
- If a model differs greatly across warehouses:
  1. Create two separate models (with the same name) in separate subdirectories, e.g. `models/bigquery/my_model.sql` and `models/default/my_model.sql`
  2. Use the `config` variable in the model to enable a model based on target type:

```
-- models/bigquery/my_model.sql
{{ config(
    enabled="{{ target.type == 'bigquery' }}"
) }}
```

In the future-future, we will do this from the `dbt_project.yml` file:
```yml
models:
  segment:
    bigquery:
      enabled: "{{ target.type == 'bigquery' }}"
    default:
      enabled: "{{ target.type != 'bigquery' }}"
```

### CODE REVIEW

**Comment by clrcrl** [comment]
BTW the git history is being preserved here, it just isn't rendering properly in the PR. If you blame a file on this branch, it has all the edits :)

**Review by jtcohen6 — APPROVED** [review]
This is a step in the right direction. We still believe that adapter macros are critical for supporting cross-db compatibility of specific functional code, but it's not a good paradigm for generating entire model SQL.

**Comment by clrcrl** [comment]
@jthandy -- can you add a ✅to confirm that we're on the same page re: best practices (as explained in the PR description)

**Comment by jthandy** [comment]
✅ 

Thanks for the great summary!! Thanks for spending the time needed to make sure we came to a great consensus here.

**Pull request merged**
