### PR TITLE
update sessionization model configs and incremental filter logic for bq

### PR DESCRIPTION
**Pull request by rjh336**
## Description & motivation
This PR attempts to address this enhancement #72 which will allow for more efficient incremental modeling in BigQuery in sessionization models.

## Notable changes
1. model configs now include `partition_by` and `cluster_by` options
2. incremental filters remove the datetime casting and add BigQuery specific logic. 

Regarding the second change I realized that #35 specifically added datetime casting for bigquery in order to make it compatible with the `dbt_utils.dateadd` macro, but this casting negates the benefit of table partitioning since BigQuery has to re-scan the full source table to do timestamp filtering. I also removed the casting for non-bigquery target types since it seemed like this was specifically put in place for bigquery and would be no longer needed. I have not been able to test whether this works on other target types so this could be a potential risk.

## Results
I compared the default incremental model options to my changes and found reductions in query time and bytes processed using a large page views table as input. [See here](https://docs.google.com/spreadsheets/d/1eMRreYFo1F2gYS5lfeHaLQx7K_YKjI5ZACHYEbqmzDc/) for results by model. 

See logs from each run:

**dbt-labs/segment:master**
```
12:05:40 | Concurrency: 2 threads (target='dev')
12:05:40 |
12:05:40 | 1 of 6 START view model dbt_rhill.segment_web_page_views............. [RUN]
12:05:41 | 1 of 6 OK created view model dbt_rhill.segment_web_page_views........ [OK in 1.01s]
12:05:41 | 2 of 6 START incremental model dbt_rhill.segment_web_page_views__sessionized [RUN]
12:05:41 | 3 of 6 START table model dbt_rhill.segment_web_user_stitching........ [RUN]
12:06:00 | 3 of 6 OK created table model dbt_rhill.segment_web_user_stitching... [CREATE TABLE (18.5m rows, 3.8 GB processed) in 19.34s]
12:07:05 | 2 of 6 OK created incremental model dbt_rhill.segment_web_page_views__sessionized [MERGE (146.8k rows, 97.2 GB processed) in 84.22s]
12:07:05 | 4 of 6 START incremental model dbt_rhill.segment_web_sessions__initial [RUN]
12:07:47 | 4 of 6 OK created incremental model dbt_rhill.segment_web_sessions__initial [MERGE (6.5k rows, 63.6 GB processed) in 41.85s]
12:07:47 | 5 of 6 START incremental model dbt_rhill.segment_web_sessions__stitched [RUN]
12:08:37 | 5 of 6 OK created incremental model dbt_rhill.segment_web_sessions__stitched [MERGE (6.5k rows, 50.7 GB processed) in 49.32s]
12:08:37 | 6 of 6 START incremental model dbt_rhill.segment_web_sessions........ [RUN]
12:09:54 | 6 of 6 OK created incremental model dbt_rhill.segment_web_sessions... [MERGE (6.5k rows, 51.1 GB processed) in 77.93s]
12:09:54 |
12:09:54 | Finished running 1 view model, 1 table model, 4 incremental models in 255.36s.

Completed successfully
```

**rjh336/segment:feature/bq-optimizations**
```
12:04:55 | Concurrency: 2 threads (target='bigquery')
12:04:55 |
12:04:55 | 1 of 6 START view model segment_integration_tests_bigquery.segment_web_page_views [RUN]
12:04:56 | 1 of 6 OK created view model segment_integration_tests_bigquery.segment_web_page_views [OK in 0.97s]
12:04:56 | 2 of 6 START incremental model segment_integration_tests_bigquery.segment_web_page_views__sessionized [RUN]
12:04:56 | 3 of 6 START table model segment_integration_tests_bigquery.segment_web_user_stitching [RUN]
12:05:17 | 3 of 6 OK created table model segment_integration_tests_bigquery.segment_web_user_stitching [CREATE TABLE (18.5m rows, 3.8 GB processed) in 20.42s]
12:07:17 | 2 of 6 OK created incremental model segment_integration_tests_bigquery.segment_web_page_views__sessionized [MERGE (146.8k rows, 81.0 GB processed) in 141.07s]
12:07:17 | 4 of 6 START incremental model segment_integration_tests_bigquery.segment_web_sessions__initial [RUN]
12:07:25 | 4 of 6 OK created incremental model segment_integration_tests_bigquery.segment_web_sessions__initial [MERGE (6.5k rows, 1.1 GB processed) in 7.55s]
12:07:25 | 5 of 6 START incremental model segment_integration_tests_bigquery.segment_web_sessions__stitched [RUN]
12:07:38 | 5 of 6 OK created incremental model segment_integration_tests_bigquery.segment_web_sessions__stitched [MERGE (6.5k rows, 1.8 GB processed) in 13.20s]
12:07:38 | 6 of 6 START incremental model segment_integration_tests_bigquery.segment_web_sessions [RUN]
12:07:46 | 6 of 6 OK created incremental model segment_integration_tests_bigquery.segment_web_sessions [MERGE (6.5k rows, 2.4 GB processed) in 8.11s]
12:07:46 |
12:07:46 | Finished running 1 view model, 1 table model, 4 incremental models in 171.80s.

Completed successfully
```

*Tested with DBT version 0.21.0*

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)

### CODE REVIEW

**Comment by rjh336** [comment]
Hi @jtcohen6, not quite sure the process for review here but please let me know any feedback when you have a chance

**Comment by joellabes** [comment]
@rjh336 thanks for opening this! And sorry for the delay in getting back to you 😢 The performance improvements in your spreadsheet are really impressive 👀 

We just merged #70 which contained some postgres-specific logic and caused a merge conflict. I don't think they'll cause significant issues with your implementation though because they're for a different adapter. Could you have a stab at integrating those changes please? 

I agree with your assessment that the changes in #35 were purely for BQ's benefit so it should be fine to remove them again.

**Comment by rjh336** [comment]
No worries @joellabes! See my updates. I decided to move adapter-specific logic to a macro called `generate_sessionization_incremental_filter`

**Review by joellabes — APPROVED** [review]
Love it! Thanks @rjh336. I'm going to change your new macro to a dispatched one (see https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch and https://github.com/dbt-labs/dbt-utils/blob/main/macros/cross_db_utils/length.sql for more info and an example). 

I just mention it as a fun thing to expose you to, but I'll do that as a separate PR. For now, let's :shipit:

**Pull request merged**
